In [1]:
import numpy as np
import pandas as pd

from math import sin, cos

In [2]:
beta = 1 - 0.1 * (52 - 50)
A = np.array([
    [10*beta, 1, -2, 3],
    [1, 10*beta, 3, 2],
    [-2, 3, 10*beta, -1],
    [3, 2, -1, 10*beta]
])
pd.DataFrame(A)

0    1    2    3
0  8.0  1.0 -2.0  3.0
1  1.0  8.0  3.0  2.0
2 -2.0  3.0  8.0 -1.0
3  3.0  2.0 -1.0  8.0

In [3]:
def get_max_indexes(A):
    buf = abs(A)
    max_elem = 0
    for i in range(buf.shape[0]):
        for j in range(buf.shape[1]):
            if i != j and max_elem < buf[i][j]:
                max_elem = buf[i][j]
                maxi, maxj = i, j
    return min(maxi, maxj), max(maxi, maxj)


def get_phi(A, index):
    return np.arctan(2*A[index[0]][index[1]] / (A[index[0]][index[0]] - A[index[1]][index[1]])) / 2.0

In [4]:
def create_Q(n, phi, index):
    Q = np.eye(n)
    Q[index[0]][index[0]] = cos(phi)
    Q[index[0]][index[1]] = -sin(phi)
    Q[index[1]][index[0]] = sin(phi)
    Q[index[1]][index[1]] = cos(phi)
    return Q

def checkA(A):
    for i in range(1, len(A)):
        print(i)
        for j in range(i, len(A)):
            print(i, j)
            if abs(A[i][j]) > 0.01:
                return False
    return True

In [5]:
Amassives = []
Qmassives = []
Amassives.append(A)

In [6]:
index = get_max_indexes(A)
phi = get_phi(A, index)
Q = pd.DataFrame(create_Q(4, phi, index)).round(decimals=4)

print('Индексы максимального по модулю недиагонального элемента:', index)
print('Максимальный по модулю недиагональный элемент:', A[index[0]][index[1]])
print('Угол поворота:', round(phi, 4))
print('Матрица Q:')
Q

Индексы максимального по модулю недиагонального элемента: (0, 3)
Максимальный по модулю недиагональный элемент: 3.0
Угол поворота: 0.7854
Матрица Q:


<ipython-input-3-1d6f15ba2c57>:13: RuntimeWarning: divide by zero encountered in double_scalars
  return np.arctan(2*A[index[0]][index[1]] / (A[index[0]][index[0]] - A[index[1]][index[1]])) / 2.0


0    1    2       3
0  0.7071  0.0  0.0 -0.7071
1  0.0000  1.0  0.0  0.0000
2  0.0000  0.0  1.0  0.0000
3  0.7071  0.0  0.0  0.7071

In [7]:
A = pd.DataFrame(np.dot(np.dot(Q.T, A), Q)).round(decimals=4)

Amassives.append(A)
Qmassives.append(pd.DataFrame(Q).round(4))

A

0       1       2       3
0  10.9998  2.1213 -2.1213  0.0000
1   2.1213  8.0000  3.0000  0.7071
2  -2.1213  3.0000  8.0000  0.7071
3   0.0000  0.7071  0.7071  4.9999

In [8]:
index = get_max_indexes(A)
phi = get_phi(A, index)
Q = pd.DataFrame(create_Q(4, phi, index)).round(decimals=4)

print('Индексы максимального по модулю недиагонального элемента:', index)
print('Максимальный по модулю недиагональный элемент:', A[index[0]][index[1]])
print('Угол поворота:', round(phi, 4))
print('Матрица Q:')
Q

Индексы максимального по модулю недиагонального элемента: (1, 2)
Максимальный по модулю недиагональный элемент: 3.0
Угол поворота: 0.7854
Матрица Q:


<ipython-input-3-1d6f15ba2c57>:13: RuntimeWarning: divide by zero encountered in double_scalars
  return np.arctan(2*A[index[0]][index[1]] / (A[index[0]][index[0]] - A[index[1]][index[1]])) / 2.0


0       1       2    3
0  1.0  0.0000  0.0000  0.0
1  0.0  0.7071 -0.7071  0.0
2  0.0  0.7071  0.7071  0.0
3  0.0  0.0000  0.0000  1.0

In [9]:
A = pd.DataFrame(np.dot(np.dot(Q.T, A), Q)).round(decimals=4)

Amassives.append(A)
Qmassives.append(pd.DataFrame(Q).round(4))

A

0        1       2       3
0  10.9998   0.0000 -2.9999  0.0000
1   0.0000  10.9998  0.0000  1.0000
2  -2.9999   0.0000  4.9999  0.0000
3   0.0000   1.0000  0.0000  4.9999

In [10]:
index = get_max_indexes(A)
phi = get_phi(A, index)
Q = pd.DataFrame(create_Q(4, phi, index)).round(decimals=4)

print('Индексы максимального по модулю недиагонального элемента:', index)
print('Максимальный по модулю недиагональный элемент:', A[index[0]][index[1]])
print('Угол поворота:', round(phi, 4))
print('Матрица Q:')
Q

Индексы максимального по модулю недиагонального элемента: (0, 2)
Максимальный по модулю недиагональный элемент: -2.9999
Угол поворота: -0.3927
Матрица Q:


0    1       2    3
0  0.9239  0.0  0.3827  0.0
1  0.0000  1.0  0.0000  0.0
2 -0.3827  0.0  0.9239  0.0
3  0.0000  0.0  0.0000  1.0

In [11]:
A = pd.DataFrame(np.dot(np.dot(Q.T, A), Q)).round(decimals=4)

Amassives.append(A)
Qmassives.append(pd.DataFrame(Q).round(4))

A

0        1       2       3
0  12.2430   0.0000  0.0001  0.0000
1   0.0000  10.9998  0.0000  1.0000
2   0.0001   0.0000  3.7575  0.0000
3   0.0000   1.0000  0.0000  4.9999

In [12]:
index = get_max_indexes(A)
phi = get_phi(A, index)
Q = pd.DataFrame(create_Q(4, phi, index)).round(decimals=4)

print('Индексы максимального по модулю недиагонального элемента:', index)
print('Максимальный по модулю недиагональный элемент:', A[index[0]][index[1]])
print('Угол поворота:', round(phi, 4))
print('Матрица Q:')
Q

Индексы максимального по модулю недиагонального элемента: (1, 3)
Максимальный по модулю недиагональный элемент: 1.0
Угол поворота: 0.1609
Матрица Q:


0       1    2       3
0  1.0  0.0000  0.0  0.0000
1  0.0  0.9871  0.0 -0.1602
2  0.0  0.0000  1.0  0.0000
3  0.0  0.1602  0.0  0.9871

In [13]:
A = pd.DataFrame(np.dot(np.dot(Q.T, A), Q)).round(decimals=4)

Amassives.append(A)
Qmassives.append(pd.DataFrame(Q).round(4))

A

0        1       2       3
0  12.2430   0.0000  0.0001  0.0000
1   0.0000  11.1624  0.0000 -0.0001
2   0.0001   0.0000  3.7575  0.0000
3   0.0000  -0.0001  0.0000  4.8378

In [32]:
Qk = pd.DataFrame(np.dot(np.dot(np.dot(Qmassives[0], Qmassives[1]), 
                                Qmassives[2]), Qmassives[3])).round(4)
Qk

0       1       2       3
0  0.6533 -0.1133  0.2706 -0.6980
1  0.2706  0.6980 -0.6533 -0.1133
2 -0.2706  0.6980  0.6533 -0.1133
3  0.6533  0.1133  0.2706  0.6980

In [33]:
np.dot(Amassives[0], Qk.iloc[:,0])

array([ 7.9981,  3.3129, -3.3129,  7.9981])

In [34]:
np.dot(np.diag(Amassives[len(Amassives) - 1])[0], Qk.iloc[:,0])

array([ 7.9983519,  3.3129558, -3.3129558,  7.9983519])

In [36]:
np.dot(Amassives[0], Qk.iloc[:,1])

array([-1.2645,  7.7913,  7.7913,  1.2645])

In [37]:
np.dot(np.diag(Amassives[len(Amassives) - 1])[1], Qk.iloc[:,1])

array([-1.26469992,  7.7913552 ,  7.7913552 ,  1.26469992])

In [38]:
np.dot(Amassives[0], Qk.iloc[:,2])

array([ 1.0167, -2.4547,  2.4547,  1.0167])

In [39]:
np.dot(np.diag(Amassives[len(Amassives) - 1])[2], Qk.iloc[:,2])

array([ 1.0167795 , -2.45477475,  2.45477475,  1.0167795 ])

In [40]:
np.dot(Amassives[0], Qk.iloc[:,3])

array([-3.3767, -0.5483, -0.5483,  3.3767])

In [41]:
np.dot(np.diag(Amassives[len(Amassives) - 1])[3], Qk.iloc[:,3])

array([-3.3767844 , -0.54812274, -0.54812274,  3.3767844 ])